<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_robot">

    <xacro:include filename="materials.xacro"/>
    <xacro:include filename="inertial_macros.xacro"/>

    <xacro:property name="base_width" value="0.4"/>
    <xacro:property name="base_height" value="0.2"/>
    <xacro:property name="link_radius" value="0.08"/>
    <xacro:property name="link_length" value="0.6"/>

    <ros2_control name="GazeboSystem" type="system">
        <hardware>
            <plugin>gazebo_ros2_control/GazeboSystem</plugin>
        </hardware>

        <joint name="joint_1">
            <command_interface name="position">
                <param name="min">-3.14</param>
                <param name="max">3.14</param>
            </command_interface>
            <state_interface name="position"/>
            <state_interface name="velocity"/>
        </joint>

        <joint name="joint_2">
            <command_interface name="position">
                <param name="min">-3.14</param>
                <param name="max">3.14</param>
            </command_interface>
            <state_interface name="position"/>
            <state_interface name="velocity"/>
        </joint>

        <joint name="joint_3">
            <command_interface name="position">
                <param name="min">-3.14</param>
                <param name="max">3.14</param>
            </command_interface>
            <state_interface name="position"/>
            <state_interface name="velocity"/>
        </joint>

        <joint name="joint_4">
            <command_interface name="position">
                <param name="min">-3.14</param>
                <param name="max">3.14</param>
            </command_interface>
            <state_interface name="position"/>
            <state_interface name="velocity"/>
        </joint>

        <joint name="joint_5">
            <command_interface name="position">
                <param name="min">-3.14</param>
                <param name="max">3.14</param>
            </command_interface>
            <state_interface name="position"/>
            <state_interface name="velocity"/>
        </joint>

        <joint name="joint_6">
            <command_interface name="position">
                <param name="min">-3.14</param>
                <param name="max">3.14</param>
            </command_interface>
            <state_interface name="position"/>
            <state_interface name="velocity"/>
        </joint>
    </ros2_control>

    <link name="base_link">
        <visual>
            <geometry>
                 <box size="${base_width} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                 <box size="${base_width} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        </collision>
        <xacro:inertial_box mass="12.0" x="${base_width}" y="${base_width}" z="${base_height}">
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    <gazebo reference="base_link">
        <material>Gazebo/Grey</material>
    </gazebo>

    <joint name="joint_1" type="revolute">
        <parent link="base_link"/>
        <child link="link_1"/>
        <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="-3.14" upper="3.14" effort="100" velocity="1.0"/>
        <dynamics damping="0.1" friction="0.1"/>
    </joint>

    <link name="link_1">
        <visual>
            <geometry>
                <cylinder radius="${link_radius}" length="0.3"/>
            </geometry>
            <origin xyz="0 0 0.15" rpy="0 0 0"/>
            <material name="orange"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${link_radius}" length="0.3"/>
            </geometry>
            <origin xyz="0 0 0.15" rpy="0 0 0"/>
        </collision>
        <xacro:inertial_cylinder mass="4.0" length="0.3" radius="${link_radius}">
            <origin xyz="0 0 0.15" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="link_1">
        <material>Gazebo/Orange</material>
    </gazebo>

    <joint name="joint_2" type="revolute">
        <parent link="link_1"/>
        <child link="link_2"/>
        <origin xyz="0 0 0.3" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit lower="-3.14" upper="3.14" effort="100" velocity="1.0"/>
        <dynamics damping="0.1" friction="0.1"/>
    </joint>

    <link name="link_2">
        <visual>
            <geometry>
                <cylinder radius="${link_radius}" length="${link_length}"/>
            </geometry>
            <origin xyz="0 0 ${link_length/2}" rpy="0 0 0"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${link_radius}" length="${link_length}"/>
            </geometry>
            <origin xyz="0 0 ${link_length/2}" rpy="0 0 0"/>
        </collision>
        <xacro:inertial_cylinder mass="2.0" length="${link_length}" radius="${link_radius}">
            <origin xyz="0 0 ${link_length/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="link_2">
        <material>Gazebo/White</material>
    </gazebo>

    <joint name="joint_3" type="revolute">
        <parent link="link_2"/>
        <child link="link_3"/>
        <origin xyz="0 0 ${link_length}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit lower="-3.14" upper="3.14" effort="100" velocity="1.0"/>
        <dynamics damping="0.1" friction="0.1"/>
    </joint>

    <link name="link_3">
        <visual>
            <geometry>
                <cylinder radius="${link_radius}" length="${link_length/1.5}"/>
            </geometry>
            <origin xyz="0 0 ${link_length/3}" rpy="0 0 0"/>
            <material name="orange"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${link_radius}" length="${link_length/1.5}"/>
            </geometry>
            <origin xyz="0 0 ${link_length/3}" rpy="0 0 0"/>
        </collision>
        <xacro:inertial_cylinder mass="2.0" length="${link_length/1.5}" radius="${link_radius}">
            <origin xyz="0 0 ${link_length/3}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="link_3">
        <material>Gazebo/Orange</material>
    </gazebo>

    <joint name="joint_4" type="revolute">
        <parent link="link_3"/>
        <child link="link_4"/>
        <origin xyz="0 0 ${link_length/1.5}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit lower="-3.14" upper="3.14" effort="100" velocity="1.0"/>
        <dynamics damping="0.1" friction="0.1"/>
    </joint>

    <link name="link_4">
        <visual>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
            <origin xyz="0 0 0.05" rpy="0 0 0"/>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
            <origin xyz="0 0 0.05" rpy="0 0 0"/>
        </collision>
        <xacro:inertial_box mass="0.5" x="0.1" y="0.1" z="0.1">
            <origin xyz="0 0 0.05" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    <gazebo reference="link_4">
        <material>Gazebo/Grey</material>
    </gazebo>

    <joint name="joint_5" type="revolute">
        <parent link="link_4"/>
        <child link="link_5"/>
        <origin xyz="0 0 0.1" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="-3.14" upper="3.14" effort="100" velocity="1.0"/>
        <dynamics damping="0.1" friction="0.1"/>
    </joint>

    <link name="link_5">
        <visual>
            <geometry>
                <cylinder radius="0.05" length="0.1"/>
            </geometry>
            <origin xyz="0 0 0.05" rpy="0 0 0"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.05" length="0.1"/>
            </geometry>
            <origin xyz="0 0 0.05" rpy="0 0 0"/>
        </collision>
        <xacro:inertial_cylinder mass="0.5" length="0.1" radius="0.05">
            <origin xyz="0 0 0.05" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="link_5">
        <material>Gazebo/White</material>
    </gazebo>

    <joint name="joint_6" type="revolute">
        <parent link="link_5"/>
        <child link="link_6"/>
        <origin xyz="0 0 0.1" rpy="0 0 0"/>
        <axis xyz="1 0 0"/>
        <limit lower="-3.14" upper="3.14" effort="100" velocity="1.0"/>
        <dynamics damping="0.1" friction="0.1"/>
    </joint>

    <link name="link_6">
        <visual>
            <geometry>
                <cylinder radius="0.08" length="0.02"/>
            </geometry>
            <origin xyz="0 0 0.01" rpy="0 0 0"/>
            <material name="orange"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.08" length="0.02"/>
            </geometry>
            <origin xyz="0 0 0.01" rpy="0 0 0"/>
        </collision>
        <xacro:inertial_cylinder mass="0.2" length="0.02" radius="0.08">
            <origin xyz="0 0 0.01" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="link_6">
        <material>Gazebo/Orange</material>
    </gazebo>

    <gazebo>
        <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">
            <parameters>$(find my_robot_description)/config/my_controllers.yaml</parameters>
        </plugin>
    </gazebo>

</robot>